version: '3.8'
services:
  golang_demo:
    image: golang_demo
    container_name: golang_demo
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
  db:
    image: mysql:8.0.21
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'roottest'
      MYSQL_DATABASE: 'golang_demo'
    volumes:
     - golang-demo-volume:/var/lib/mysql

volumes:
  golang-demo-volume: