version: '3'
services:
  db:
    image: mysql:8.0.21
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'roottest'
      MYSQL_DATABASE: 'golang_demo'