version: '3.8'
services:
  golang_demo:
    image: golang_demo
    container_name: golang_demo
    build: ./docker
    ports:
      - 8080:8080
    volumes:
      - .:/app
  db:
    image: mysql:8.0.21
    container_name: golang_demo_db
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'roottest'
      MYSQL_DATABASE: 'golang_demo'
    volumes:
     - golang-demo-volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=test
      - PMA_PASSWORD=test
    ports:
      - "8088:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

volumes:
  golang-demo-volume: